export const MAINNAVBAR = "MAINNAVBAR";
export const LOGO = "LOGO";
export const DEPARTMENTS = "DEPARTMENTS";
export const NAVBARLOGGERS = "NAVBARLOGGERS";
export const LOGGERDEPARTMENTS = "LOGGERDEPARTMENTS";
export const DEPARTMENT = "DEPARTMENT";
export const MENUICON = "MENUICON";
export const MOBILEDEPARTMENT = "MOBILEDEPARTMENT";
